### ISSUE TITLE
Demande d'explication sur la gestion des requêtes

### ISSUE THREAD

**Issue by alexdp** [forax/jexpress#1]
Bonjour Monsieur Forax,

Je me vous contacte car je suis très intrigué car votre implémentation express.js en java. Je n'arrive pas à voir dans le code comment sont gérés les appels concurrents. Je vois bien les callbacks mais j'ai l'impression que le serveur ne peut répondre qu'à une requête à la fois. 

Pourriez-vous m'éclairer (simplement) ?

Merci beaucoup,
Alexandre

**Comment by forax** [comment]
Bonjour,
effectivement, le serveur répond une requète à la fois
https://github.com/forax/jexpress/blob/master/src/JExpress.java#L411

ce code n'est pas fait pour être utilisé en production !

**Comment by forax** [comment]
Avec Loom, il y a un maintenant une version avec plusieurs threads virtuelles mais une seul thread platform
(donc pas de problème de concurrence)
https://github.com/forax/jexpress/blob/master/src/main/java/JExpressLoom.java

---

With Loom, there is now a variant using several virtual threads but only platform thread
(so no concurrency issue)
https://github.com/forax/jexpress/blob/master/src/main/java/JExpressLoom.java

This code should still not be used in production :)

I think i can close that issue now.
